apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T12:54:55Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "5006"
  uid: 034a5d0e-9d97-4a1a-851f-cb9270ecc577
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.127.181
  clusterIPs:
  - 10.101.127.181
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31939
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
